---
version: 2.1

executors:
  base:
    docker:
    - image: cimg/base:stable-20.04

jobs:
  build:
    executor: base

    steps:
    - checkout
    - run: sudo apt-get update
    - run: sudo apt-get install -y cmake g++ git make libglib2.0-dev zlib1g-dev libpcre3-dev libssl-dev libzstd-dev wget
    - run: wget https://repo.percona.com/apt/percona-release_latest.focal_all.deb
    - run: dpkg -i percona-release_latest.focal_all.deb
    - run: percona-release setup -y ps80
    - run: sudo apt-get install -y libperconaserverclient21 percona-server-server libperconaserverclient21-dev
    - run: cmake .
    - run: make
    - run: ./mydumper --version

workflows:
  version: 2
  mydumper:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
