---
version: 2.1

executors:
  base:
    docker:
    - image: cimg/base:stable-20.04
      environment:
        MYSQL_HOST: 127.0.0.1
        MYSQL_DB: mate
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_PASSWORD:
    - image: percona:8
      command: mysqld
      environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: /tmp/mydumper/

commands:
  prepare_ubuntu:
    steps:
    - checkout
    - run: sudo apt-get update
    - run: sudo apt-get install -y cmake g++ git make libglib2.0-dev zlib1g-dev libpcre3-dev libssl-dev libzstd-dev
    - run: wget https://repo.percona.com/apt/percona-release_latest.focal_all.deb
    - run: sudo dpkg -i percona-release_latest.focal_all.deb
    - run: sudo percona-release setup -y ps80
    - run: sudo apt-get install -y libperconaserverclient21 libperconaserverclient21-dev percona-server-client
    - run: cmake .
    - run: make
    - run: ./mydumper --version
    # - run: bash ./test_mydumper.sh SSL GZIP
    - run: cmake . -DWITH_ZSTD=ON
    - run: make
    - run: ./mydumper --version
    # - run: bash ./test_mydumper.sh SSL ZSTD

jobs:
  build:
    executor: base
    environment:
      FOO: bar
    steps:
    - checkout
    - prepare_ubuntu
    - persist_to_workspace:
         root: /tmp/src/mydumper
         paths:
           - .
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/src/mydumper
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(mydumper --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/package

workflows:
  version: 2
  mydumper:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - publish-github-release:
        requires:
          - build
        filters:
          tags:
            only: /.*/
