name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
              
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mydumper/mydumper

      - name: Testing
        shell: bash
        run: |
          echo "TAGS: $TAGS"
          echo "LABELS: $LABELS"

        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}


      - name: Build and push Docker image GZIP
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: remove latest on tags 
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{ steps.meta.outputs.tags }}
          labels: latest
          type: remove
  
      - name: remove latest on labels
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{ steps.meta.outputs.labels }}
          labels: latest
          type: remove

      - name: Build and push Docker image ZSTD
        uses: docker/build-push-action@v4
        with:
          build-args: CMAKE_ARGS=-DWITH_ZSTD=ON
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}-zstd , latest-zstd
          labels: ${{ steps.meta.outputs.labels }}-zstd , latest-zstd


