name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build el9 image
      run: docker build . --file docker/el9/Dockerfile --tag mydumper-builder-el9:$(date +%s)
